server.port=${PORT:8080}
spring.application.name=Veritas-AI

# Database Configuration using Render Environment Variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Connection Pooling (Crucial for Clever Cloud Free Plan)
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true